language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true

addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - yarn lint
  - yarn flow
  - yarn test --coverage
  - yarn build:prod
  - yarn build:dist --publish "never"
  - yarn test-e2e
  - yarn codecov